
spring:
  datasource:
    hikari:
      jdbc-url: "jdbc:postgresql://localhost:5432/webinar_database?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
      maximum-pool-size: 10
      driver-class-name: org.postgresql.Driver
    username: test
    password: root
    url: "jdbc:postgresql://localhost:5432/webinar_database?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
    driver-class-name: org.postgresql.Driver

---

amazon:
  images:
    s3: 123123213
    token: someToken
    password: password

google:
  video:
    in6: ROCK SOUND
    password: 123456789
    city: Grodno